format_version: 5
pipelines:
  spring-boot-helloworld-simple:
    group: simple
    materials:
      spring-boot-hello-world:
        git: https://github.com/arunvelsriram/spring-boot-helloworld.git
        branch: master
    stages:
      - build:
          jobs:
            test:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - testCoverage
  spring-boot-helloworld-docker:
    group: docker
    materials:
      spring-boot-hello-world:
        git: https://github.com/arunvelsriram/spring-boot-helloworld.git
        branch: master
    stages:
      - build:
          jobs:
            test:
              tasks:
                - exec:
                    command: docker
                    arguments:
                      - run
                      - --rm
                      - -v
                      - "$PWD:/app"
                      - --entrypoint
                      - /app
                      - adoptopenjdk/openjdk11
                      - "./gradlew testCoverage"
